version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./config.yaml:/gidbig/config.yaml
            - ./plugins:/gidbig/plugins
            - ./audio:/gidbig/audio
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
            interval: 30s
            timeout: 5s
            retries: 3
