name: Check and build

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    preparation:
        name: Prepare environment
        runs-on: ubuntu-latest

        outputs:
            go_version: ${{ steps.determine_go_version.outputs.go_version }}

        steps:
            - uses: actions/checkout@v4

            - name: Determine Go version from go.mod
              id: determine_go_version
              run: echo "go_version=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_OUTPUT

    check_code:
        name: Check code
        needs: preparation
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ needs.preparation.outputs.go_version }}

            - name: Install dependencies
              run: |
                  go version
                  go get -u golang.org/x/lint/golint
                  export PATH=${PATH}:$(go env GOPATH)/bin

            - name: Lint
              uses: golangci/golangci-lint-action@v6

    build:
        name: Build
        needs:
            - check_code
            - preparation
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ needs.preparation.outputs.go_version }}

            - name: Run build
              run: make build

    deploy_for_testing:
        name: Deploy for testing
        if: ${{ github.ref == 'refs/heads/testing' }}
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Dispatch Deploy Repo
              uses: peter-evans/repository-dispatch@v2.1.2
              with:
                  token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
                  repository: toksikk/deploy-gidbig
                  event-type: deploy
